
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftMULTIPLYDIVIDErightUMINUSDIVIDE LPAREN MINUS MULTIPLY NUMBER PERCENT PLUS RPAREN SQRTexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression MULTIPLY expression\n                  | expression DIVIDE expressionexpression : SQRT expressionexpression : expression PERCENTexpression : LPAREN expression RPARENexpression : NUMBERexpression : MINUS expression %prec UMINUS'
    
_lr_action_items = {'SQRT':([0,2,3,4,6,7,8,9,],[3,3,3,3,3,3,3,3,]),'LPAREN':([0,2,3,4,6,7,8,9,],[4,4,4,4,4,4,4,4,]),'NUMBER':([0,2,3,4,6,7,8,9,],[5,5,5,5,5,5,5,5,]),'MINUS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,],[2,7,2,2,2,-8,2,2,2,2,-6,-9,7,7,-1,-2,-3,-4,-7,]),'$end':([1,5,10,11,12,14,15,16,17,18,],[0,-8,-6,-9,-5,-1,-2,-3,-4,-7,]),'PLUS':([1,5,10,11,12,13,14,15,16,17,18,],[6,-8,-6,-9,6,6,-1,-2,-3,-4,-7,]),'MULTIPLY':([1,5,10,11,12,13,14,15,16,17,18,],[8,-8,-6,-9,8,8,8,8,-3,-4,-7,]),'DIVIDE':([1,5,10,11,12,13,14,15,16,17,18,],[9,-8,-6,-9,9,9,9,9,-3,-4,-7,]),'PERCENT':([1,5,10,11,12,13,14,15,16,17,18,],[10,-8,-6,-9,10,10,-1,-2,-3,-4,-7,]),'RPAREN':([5,10,11,12,13,14,15,16,17,18,],[-8,-6,-9,-5,18,-1,-2,-3,-4,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,3,4,6,7,8,9,],[1,11,12,13,14,15,16,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','calculadora.py',64),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','calculadora.py',65),
  ('expression -> expression MULTIPLY expression','expression',3,'p_expression_binop','calculadora.py',66),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','calculadora.py',67),
  ('expression -> SQRT expression','expression',2,'p_expression_sqrt','calculadora.py',83),
  ('expression -> expression PERCENT','expression',2,'p_expression_percent','calculadora.py',87),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','calculadora.py',91),
  ('expression -> NUMBER','expression',1,'p_expression_number','calculadora.py',95),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','calculadora.py',99),
]
